class ImageDithering:
	def count(self, dithered, screen):
		li1 = list(dithered)
		count = 0
		for row in screen:
			for pixel in list(row):
				count+=1 if pixel in li1 else 0

		return count

test = ImageDithering()
print test.count("CA", ("BBBBBBBB","BBBBBBBB","BBBBBBBB"))
print test.count("ACEGIKMOQSUWY", ("ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX","ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX", "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX"))